### ISSUE TITLE
Sometimes a "}" is automatically added at the end of the note.

### ISSUE THREAD

**Issue by ouatis** [dartungar/obsidian-simple-note-review#11]
Very good plugin! Perfect for my needs! 

I found a small problem while using it on v.1.0.0.

If a note does not have YAML, when I use mark note as reviewed today, a "}" is automatically added at the end of the note. Instead of just adding a YAML.

However, if a note comes with YAML, there is no such problem.

I've also tested turning off other plugins (besides the necessary Dataview) and still have this problem.

I hope you have time to fix it. Thanks for your work. 👍

**Comment by dartungar** [comment]
Thanks for the report (and the kind words)!
I've reproduced the problem, will fix it as soon as I have spare time.
