### ISSUE TITLE
Marking as review opening already reviewed notes

### ISSUE THREAD

**Issue by emiliobool** [dartungar/obsidian-simple-note-review#15]
Is this the expected behavior? I added a note set "All Notes", I left the tags and folders fields empty

Then when marking a note as reviewed it shows me a note I have already reviewed recently even when I have plenty of notes I haven't reviewed yet

<img width="791" alt="CleanShot 2022-10-20 at 18 24 43@2x" src="https://user-images.githubusercontent.com/2165828/197089934-6c58fc07-1cd7-4bb0-8aa4-d33242c91ed0.png">

marking as reviewed keeps showing me reviewed notes

Thank you

**Comment by dartungar** [comment]
This is really strange. Have you tried to disable and then enable the
plugin (and dataview as well)?

пт, 21 окт. 2022 г., 06:31 emiliobool ***@***.***>:

**Comment by emiliobool** [comment]
I restarted obsidian completely and that didn't work, but then I updated all plugins and it worked properly, so I was probably on an old version, thank you!
