### ISSUE TITLE
Notes marked as "ignore" still appear with the default algorithm

### ISSUE THREAD

**Issue by ouatis** [dartungar/obsidian-simple-note-review#16]
Hello! I've been using this plugin for about a week now.

I toggled the _Use review frequency_ option and marked several notes as "ignore", but I can confirm that they still appear with the default algorithm, out of my 1000+ notes.

Please check to see if there is something wrong. Thanks for your work! :)

**Comment by dartungar** [comment]
@ouatis thanks for the report. will look into it as soon as I get some free time. cheers!

**Comment by ouatis** [comment]
One more little problem...

_Use review frequency_ option still toggled. It seems that after clicking _Mark Note As Reviewed Today_, it automatically adds a "review-frequency: normal" right above the second "---" of the YAML front matter.

In this case, if a note additionally uses "---" as a split line, the review-frequency line will be added above the split line, instead of inside the YAML, which is a bit annoying.

These two issues don't really affect my daily use much. So please take your time!

**Comment by dartungar** [comment]
should be fixed in 0.5.6.
