### ISSUE TITLE
`Open next note in the note set after reviewing a note` reverts to `TRUE` after restarting Obsidian

### ISSUE THREAD

**Issue by stefanherzog** [dartungar/obsidian-simple-note-review#18]
The setting `Open next note in the note set after reviewing a note` reverts to (the default?) `TRUE` after restarting Obsidian even though I set it to `FALSE`. Expected behavior: The user's setting is retained when restarting the app.

This happens in Obsidian 1.0.3 (but likely already in earlier version, but can't say fore sure).

**Comment by dartungar** [comment]
should be fixed in 0.5.7.

(.net made me lazy - these kinds of errors just will not compile there :P )

**Comment by stefanherzog** [comment]
Thanks! Can confirm that the setting is now preserved after restarting the app.
