### ISSUE TITLE
Empty set (BUG) ⭕

### ISSUE THREAD

**Issue by PhoenixBodrov** [dartungar/obsidian-simple-note-review#22]
Windows 10, dataview installed. Clearly you can see a whole bunch of files. I don't know what to do 😞

![изображение](https://user-images.githubusercontent.com/100290554/208269560-0429dc6c-7dc1-4ef5-ab16-9e185cf6d169.png)
![изображение](https://user-images.githubusercontent.com/100290554/208269587-8387434a-7951-44b9-b808-a2d28888e976.png)
![изображение](https://user-images.githubusercontent.com/100290554/208269593-24326b1d-e499-40af-9b69-b2196623e911.png)
![изображение](https://user-images.githubusercontent.com/100290554/208269594-d6e9f809-72f7-4585-96c5-0f7b6036dc19.png)

**Comment by dartungar** [comment]
@PhoenixBodrov yeah, apparently Dataview can not process top-level folders with "/" before their name. So, instead of "/Входящие", you should use "Входящие". 
I've updated settings description & screenshots in readme accordingly.
