### ISSUE TITLE
FR: Add command to open a review note with last configured note set

### ISSUE THREAD

**Issue by MMoMM-org** [dartungar/obsidian-simple-note-review#23]
I would like to open a review note without specifying the note set all the time.

it could either be a default note set or the note set configured by the command available at the moment.

**Comment by dartungar** [comment]
@MMoMM-org this **is** on the roadmap! Will work on that as soon as I get some time on my hands.

**Comment by dartungar** [comment]
@MMoMM-org will be out in 0.6.0.
