### ISSUE TITLE
Cannot mark note as reviewed in Reading mode

### ISSUE THREAD

**Issue by eudroid** [dartungar/obsidian-simple-note-review#27]
I cannot Mark Note As Reviewed Today nor Set review frequency in Reading mode by using hotkeys or command palette. (Version 0.6.1)

**Comment by dartungar** [comment]
@eudroid this is known behavior; probably has to do with mobile app itself. Unfortunately I can't debug mobile app, so it's hard to say when this gets resolved.

**Comment by mattstam** [comment]
@dartungar This is also the case for desktop versions of the app too. "Mark as reviewed" on current note does not work if on reading mode.

**Comment by dartungar** [comment]
@dartungar could you provide some specifics - Obsidian version, planform you are working on, etc?
Just checked on Windows 11, Obsidian 1.1.9 - marking note as reviewed today while in reading mode works just fine!

**Comment by eudroid** [comment]
@dartungar I ran into issue on Windows 10 Home, Obsidian 1.1.9, SNR 0.6.2 and all other plugins disabled except Dataview

**Comment by dartungar** [comment]
@eudroid this is strange indeed. I will try to reproduce it.

**Comment by eudroid** [comment]
Thank you, great job!
