### ISSUE TITLE
Review date is incorrect for some timezones

### ISSUE THREAD

**Issue by ontrou** [dartungar/obsidian-simple-note-review#29]
How is the date in the `Mark Note As Reviewed Today` calculated? When I invoke it, it always sets a date one day in the future.

**Comment by dartungar** [comment]
@ontrou Today is always today. If it doesn't, it's a bug! However, I can't reproduce it. What timezone are you in?

**Comment by ontrou** [comment]
PST time zone (UTC -8). It seems to happen only in the evening; during the day the reviewed date is correct. I also tested the plugin in a test vault and with all other plugins (except Dataview) deactiviated. Same issue.

**Comment by dartungar** [comment]
@ontrou this may happen because time is not adjusted for time zone (probably defaulting to GMT+0). Will look into it!

**Comment by dartungar** [comment]
@ontrou  should be fixed in 0.6.2!
JS sure is a weird language.
