### ISSUE TITLE
How to skip notes while reviewing?

### ISSUE THREAD

**Issue by Gabriel2409** [dartungar/obsidian-simple-note-review#45]
## Context

Hello and thank you for creating this plugin.

I am using the "obsidian-simple-note-review" plugin to review notes of varying lengths. Occasionally, I come across lengthy notes that I'd like to skip temporarily while retaining them in the review queue without updating their review date.

## Issue

Currently, when I click the "Next" button, it advances to the next note in the queue. However, if I click it again, it returns to the first note in the list. From my understanding, this behavior is due to the fact that, in the `getNextFilePath` function of the plugin, the implementation sets the `firstNoteIndex` to 0.

https://github.com/dartungar/obsidian-simple-note-review/blob/ec498befe31342583403f4225dc7270ba221d661/src/noteSet/noteSetService.ts#L168C1-L178C14

## Possible implementation

To address this issue, I suggest implementing the following change in the `noteSetService`:
- Maintain a record of the latest skipped note index when not using the random algorithm. This way, instead of always starting at index 0, you can start at the latest skipped index + 1. 
- Reset the skip index under specific conditions, such as when the user actively chooses not to skip a note (e.g., by not clicking the skip button).

## Follow up

Do you think adding this feature to the plugin is a good idea? 
If so, would you be willing to add it yourself or accept pull requests?

**Comment by dartungar** [comment]
@Gabriel2409 hey, thanks for the thorough suggestion!

The main premise of SNR is not to have any state, just noteset descriptions, so they will be calculated "on the fly" via Dataview API. Note sets are not queues, nor should they be (in my vision).

Adding "skip" functionality will require complicating the logic and making Simple Note Review not so simple, so I don't think this feature will be a good addition to the plugin (however convenient it is). I think there are some spaced repetition plugins that probably have this kind of functionality.

As a workaround, you can set review date on the note to later one (line +10 days of current value), so it will be skipped by algorithm when calculating the next note.

Cheers!

**Comment by Gabriel2409** [comment]
That makes sense.
I agree that state management can be a pain.

Thank you for taking the time to answer, I will use your workaround :)

**Comment by dartungar** [comment]
@Gabriel2409 it's implemented in version 1.0.1. Cheers!
