### ISSUE TITLE
If there are '---' in file, review-frequency property is not added properly

### ISSUE THREAD

**Issue by abinmn** [dartungar/obsidian-simple-note-review#46]
In some of my notes I use a line break to add metadata about some notes. On such notes when I set the review frequency, the plugin insert the text on top of this line break instead of properties. 

I'm assuming since the frontmatter also ends with '---' the plugin is confused between frontmatter and actual line breaks. 

<img width="925" alt="image" src="https://github.com/dartungar/obsidian-simple-note-review/assets/29946484/3734b50e-2f4e-4121-9042-685266b451cb">

**Comment by dartungar** [comment]
@abinmn this happens sometimes, will hopefully get to this soon. Personally I use "***" for line breaks and "###" for headings, so this bug went unnoticed. Cheers.

**Comment by dartungar** [comment]
@abinmn this happened when you had empty but existing metadata section; should be fixed in 1.1.0.
