### ISSUE TITLE
Question about filtering

### ISSUE THREAD

**Issue by edward-peters** [dartungar/obsidian-simple-note-review#56]
Thank you for your plug in which is super useful.
I want to use it for reviewing books I have read, but I use a Property (status=completed) not a tag to indicate what is read. 
Is there a way to filter on that property, so that only book notes which do not have the key 'completed' in the property 'status' are included in the review queue?

**Comment by dartungar** [comment]
@edward-peters I don't think this is possible now. I will probably implement something like this in the future, but no ETA yet.
