### ISSUE TITLE
Unidentified validation errors

### ISSUE THREAD

**Issue by brightTurban** [dartungar/obsidian-simple-note-review#58]
Hello dartungar! 

First of all I want to thank you for your great work! I find your plugin very useful for my academic life. However I encountered a problem about particular folder. I think that's a problem in path specification. In the images I tried to be detailed in providing sufficient context and describing the problem. I can't review a particular note for unspecified reasons 

<img width="1440" alt="Screenshot 2024-01-29 alle 23 29 46" src="https://github.com/dartungar/obsidian-simple-note-review/assets/100793746/cc2a9cd1-1bb9-466b-bf07-2a7d710514f7">
<img width="1440" alt="Screenshot 2024-01-29 alle 23 29 52" src="https://github.com/dartungar/obsidian-simple-note-review/assets/100793746/6949a9e7-038e-459f-bff0-33def96e62d8">
<img width="1440" alt="Screenshot 2024-01-29 alle 23 30 07" src="https://github.com/dartungar/obsidian-simple-note-review/assets/100793746/8c3ba7dc-1bf1-4b30-8ef1-ab29ccb7dc8a">
<img width="1440" alt="Screenshot 2024-01-29 alle 23 30 28" src="https://github.com/dartungar/obsidian-simple-note-review/assets/100793746/abdfe111-a899-409f-b3c7-71521430d450">
<img width="1440" alt="Screenshot 2024-01-29 alle 23 30 58" src="https://github.com/dartungar/obsidian-simple-note-review/assets/100793746/7968e782-fa84-4e2c-91a9-3fc78523ab5a">

**Comment by dartungar** [comment]
@brightTurban thanks for the detailed bug report! A pleasure to my eyes.
There was a bug that prevented empty notesets from updating properly; it should be fixed in 1.2.1.
Please check if the problem persists!
