### ISSUE TITLE
Obsidian “Excluded files” configuration is ignored

### ISSUE THREAD

**Issue by DDzwiedziu** [dartungar/obsidian-simple-note-review#69]
I have integrated Logseq to my vault and set Obsidian to ignore the Logseq-specific folder. Despite that SNR is adding notes from that folder to be reviewed.

![image](https://github.com/user-attachments/assets/f3d42e39-7852-4c2f-b005-9b937d137905)

Edit: sorry, false alarm. Not “nice” on my part.

**Comment by dartungar** [comment]
@DDzwiedziu no problem - I see where you're coming from 👍 
But yeah, respecting Obsidian's ignored folders might be tricky to implement...if possible at all (I'll have to look at the API to see if Obsidian exposes this info at all)
